---
title: "Readiness to Disclose Pediatric HIV Status to Children"
output:
  html_document:
    toc_float: false
---

*In 2013, our team of researchers from Duke University, George Mason University, REPSSI, BHASO, and the University of Zimbabwe began a study funded by the Eunice Kennedy Shriver National Institute of Child Health and Human Development (5R21HD076695-03) to develop a tool that counselors could use to assess and monitor a caregiver’s readiness and self-efficacy to disclose a child's serostatus to the child. We created this study website to store all study-related products and data (licensed under the [CC-BY license](https://creativecommons.org/licenses/by/4.0/)). New material will be released as academic manuscripts enter production.*

* * * 

An estimated 2.1 million children are living with HIV (2015), but it is unclear how many know it. Young people often test positive and begin antiretroviral therapy without learning why they are sick, the nature of their illness, or the purpose of the medication. Research suggests that children who are not told that they have a serious health condition exhibit lower adherence to treatment and poorer health outcomes than those who are aware of their status. Conversely, children who know their status exhibit higher self-esteem, fewer behavior problems, and less psychological distress. After disclosure, children may also have improved social functioning, more social support, more positive attitudes about their health, better health outcomes, and more hope for the future. 

While international guidance recommends that school-age children should be informed of their serostatus, disclosure can be complex and difficult for caregivers who often believe that their child is too young, that disclosing may cause psychological harm, or that the child and family will be exposed to stigma. Healthcare providers can be an important source of support for caregivers as they struggle with the decision to disclose and the process of disclosure; however, providers need training and tools to make sure that the support that they provide is effective in improving the ability of caregivers to disclose. While there is a small but growing body of evidence supporting disclosure interventions, tailoring the interventions for the specific needs of caregivers remains a challenge. To tailor effectively, we need to understand how ready a caregiver is to disclose and how confident they feel about disclosure in order to meet the caregiver where they are in the process.