---
title: "Team"
output:
  html_document:
    toc_float: false
---

This study is led by Dr. Eric Green and Dr. Katie Schenk. [Green](https://globalhealth.duke.edu/people/faculty/green-eric) is on the faculty at Duke University in the Duke Global Health Institute, and [Schenk](https://chhs.gmu.edu/faculty-and-staff/schenk.cfm) is a Research Assistant Professor in the Department of Global and Community Health at George Mason University. Dr. Lisa Langhaug and Dr. Eve Puffer are Co-Investigators on the study. [Langhaug](https://www.linkedin.com/in/lisa-langhaug-148b041b/) is the former Head of Research for REPSSI, and [Puffer](https://psychandneuro.duke.edu/people/eve-s-puffer) is on the faculty at Duke University with a joint appointment in the Duke Global Health Institute and the Department of Psychology and Neuroscience.

The study team is advised by Dr. Simbarashe Rusakaniko and Dr. Kathleen Sikkema. [Rusakaniko](http://www.uz.ac.zw/index.php/chs-departments/263-community-medicine/community-medicinestaff/682-professor-simbarashe-rusakaniko) is a Professor of Biostatistics, Research & Epidemiology in the Department of Community Medicine at the University Zimbabwe, and he directs the ZAPP Trust and the Centre for Research & Training in Clinical Epidemiology & Biostatistics. [Sikkema](https://globalhealth.duke.edu/people/faculty/sikkema-kathleen) is a Professor of Psychology and Neuroscience, Global Health, and Psychiatry and Behavioral Sciences at Duke University. Rusakaniko also heads a National Advisory Committee whose members included Raymond Yekeye, Gertrude Ncube, and Mucha Mukamuri.

Research support is provided by Simba Mahaso, Dr. Amy Finnegan, Dr. Joshua Wiley, and Yujung Choi. Mahaso directs the [Batanai HIV & AIDS Service Organisation](http://www.bhaso.org/) (BHASO) and coordinated our engagement with the local community. [Finnegan](https://sites.google.com/site/amyfinnegan/home) is a Postdoctoral Research Associate in the Duke Global Health Institute, and [Choi](https://www.linkedin.com/in/yujung-choi-a5749438/) is a recent graduate of the Masters of Science in Global Health program. [Wiley](http://joshuawiley.com/) is a lecturer in the Monash Institute of Cognitive and Clinical Neurosciences and School of Psychological Sciences at Monash University.

The following individuals made important contributions to the study: Katey King, Stephanie Banks, Kiera Needham, Sibusisiwe Sibanda, Tendai Losi, Marjorie Madamombe, Rerusai Hove, Getrude Kunzwa, Alice Machaya, Faustine Mupoperi, Memory Mabutho, Valerie Pfupajena, Tendai Makanjera, and Memory Makamba.